name: base
channels:
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anaconda-anon-usage=0.4.4
  - archspec=0.2.3
  - blas=1.0
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - conda=24.9.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=24.9.0
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - cryptography=43.0.0
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - distro=1.9.0
  - expat=2.6.3
  - ffmpeg=4.3
  - fmt=9.1.0
  - freetype=2.12.1
  - frozendict=2.4.2
  - giflib=5.2.2
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - jsonpatch=1.33
  - jsonpointer=2.1
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libarchive=3.7.4
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.11.1.6
  - libcurand=10.3.7.77
  - libcurl=8.9.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.57.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libsolv=0.7.24
  - libssh2=1.11.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - menuinst=2.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.15
  - packaging=24.1
  - pcre2=10.42
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.12.7
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.3
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tqdm=4.66.5
  - truststore=0.8.0
  - typing_extensions=4.11.0
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - alembic==1.15.1
      - annotated-types==0.7.0
      - anyio==4.9.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - bcrypt==4.3.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - cachetools==5.5.2
      - click==8.1.8
      - comm==0.2.2
      - contextvars==2.4
      - contourpy==1.3.1
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - datasets==3.2.0
      - debugpy==1.8.9
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - executing==2.1.0
      - fake-useragent==2.2.0
      - fastapi==0.115.0
      - fastjsonschema==2.21.0
      - filelock==3.16.1
      - filetype==1.2.0
      - fonttools==4.55.0
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - google-ai-generativelanguage==0.6.17
      - google-api-core==2.24.2
      - google-api-python-client==2.166.0
      - google-auth==2.38.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.1
      - google-genai==1.9.0
      - google-generativeai==0.8.4
      - googleapis-common-protos==1.69.2
      - greenlet==3.1.1
      - grpcio==1.71.0
      - grpcio-status==1.71.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httplib2==0.22.0
      - httptools==0.6.4
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.27.0
      - immutables==0.21
      - inquirerpy==0.3.4
      - ipykernel==6.29.5
      - ipython==8.29.0
      - isoduration==20.11.0
      - jedi==0.19.2
      - joblib==1.5.1
      - json5==0.10.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.7
      - loguru==0.7.3
      - lxml==5.4.0
      - mako==1.3.9
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - notebook-shim==0.2.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oauthlib==3.2.2
      - orjson==3.10.16
      - ormsgpack==1.9.1
      - overrides==7.7.0
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - passlib==1.7.4
      - pexpect==4.9.0
      - pfzy==0.3.4
      - pgvector==0.4.1
      - playwright==1.52.0
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.48
      - propcache==0.2.1
      - proto-plus==1.26.1
      - protobuf==5.29.4
      - psutil==6.1.0
      - psycopg2-binary==2.9.10
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydantic-settings==2.8.1
      - pyee==13.0.0
      - pygments==2.18.0
      - pyjwt==2.10.1
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - python-multipart==0.0.20
      - pytz==2024.2
      - pyzmq==26.2.0
      - redis==5.2.1
      - referencing==0.35.1
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.21.0
      - rsa==4.9
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.39
      - stack-data==0.6.3
      - starlette==0.38.6
      - sympy==1.13.1
      - tenacity==9.1.2
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tiktoken==0.8.0
      - tinycss2==1.4.0
      - torch==2.5.1
      - torchviz==0.0.3
      - tornado==6.4.2
      - traitlets==5.14.3
      - triton==3.1.0
      - types-python-dateutil==2.9.0.20241003
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - uri-template==1.3.0
      - uritemplate==4.1.1
      - uvicorn==0.30.6
      - uvloop==0.21.0
      - watchfiles==1.0.4
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - xxhash==3.5.0
      - yarl==1.18.3
