"""empty message

Revision ID: 15b397869d7c
Revises: a178176b4df8
Create Date: 2025-05-25 18:27:25.873504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15b397869d7c'
down_revision: Union[str, None] = 'a178176b4df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE public.newssummaryperiod ADD VALUE 'daily'")
    op.add_column('news_summary_entry', sa.Column('creation_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_summary_entry', 'creation_time')
    # ### end Alembic commands ###
