"""empty message

Revision ID: 4231794b9b2b
Revises: 6e8c2122548c
Create Date: 2025-05-10 09:16:18.591750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import vector


# revision identifiers, used by Alembic.
revision: str = '4231794b9b2b'
down_revision: Union[str, None] = '6e8c2122548c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_entries', sa.Column('summary_embedding', vector.VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_entries', 'summary_embedding')
    # ### end Alembic commands ###
