"""empty message

Revision ID: 47b6bf45d96e
Revises: f2b2d24f4355
Create Date: 2025-06-21 21:04:17.171974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b6bf45d96e'
down_revision: Union[str, None] = 'f2b2d24f4355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_summary_entry', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_summary_entry', 'category')
    # ### end Alembic commands ###
