"""empty message

Revision ID: 524f5e7b073d
Revises: 9af681943909
Create Date: 2025-04-25 19:34:58.217037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.db.models.common import LangChainMessageType, ConversationType


# revision identifiers, used by Alembic.
revision: str = '524f5e7b073d'
down_revision: Union[str, None] = '9af681943909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    lang_chain_message_type = sa.Enum(LangChainMessageType, name="langchainmessagetype")
    lang_chain_message_type.create(op.get_bind(), checkfirst=True)
    conversation_type = sa.Enum(ConversationType, name="conversationtype")
    conversation_type.create(op.get_bind(), checkfirst=True)
    op.add_column('conversation_history', sa.Column('lang_chain_message_type', lang_chain_message_type, nullable=True))
    op.add_column('conversation_history', sa.Column('conversation_type', conversation_type, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_history', 'conversation_type')
    op.drop_column('conversation_history', 'lang_chain_message_type')
    # ### end Alembic commands ###
