"""empty message

Revision ID: 5525e38a8016
Revises: babf4dff2f10
Create Date: 2025-06-02 18:01:42.017502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5525e38a8016'
down_revision: Union[str, None] = 'babf4dff2f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('logical_key', table_name='news_summary_entry')
    op.create_index('news_summary_entry_logical_key', 'news_summary_entry', ['user_id', 'start_date', 'period_type', 'news_chunking_experiment', 'news_preference_application_experiment', 'display_order_within_period'], unique=True)
    op.add_column('news_summary_experiment_stats', sa.Column('shown', sa.Boolean(), nullable=True))
    op.create_index('news_summary_experiment_stats_logical_key', 'news_summary_experiment_stats', ['user_id', 'start_date', 'period_type', 'news_chunking_experiment', 'news_preference_application_experiment'], unique=True)
    op.add_column('users', sa.Column('preferred_news_summary_period_type', sa.Enum('daily', 'weekly', 'monthly', name='newssummaryperiod'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_news_summary_period_type')
    op.drop_index('news_summary_experiment_stats_logical_key', table_name='news_summary_experiment_stats')
    op.drop_column('news_summary_experiment_stats', 'shown')
    op.drop_index('news_summary_entry_logical_key', table_name='news_summary_entry')
    op.create_index('logical_key', 'news_summary_entry', ['user_id', 'start_date', 'period_type', 'news_chunking_experiment', 'news_preference_application_experiment', 'display_order_within_period'], unique=True)
    # ### end Alembic commands ###
