"""empty message

Revision ID: 5de3f80aea9c
Revises: 780d22ff8724
Create Date: 2025-03-21 15:57:31.275546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.db.models.common import UserStatus

# revision identifiers, used by Alembic.
revision: str = '5de3f80aea9c'
down_revision: Union[str, None] = '780d22ff8724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    user_status = sa.Enum(UserStatus, name="userstatus")
    user_status.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status',user_status, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    user_status = sa.Enum(UserStatus, name="userstatus")
    user_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
