"""news summary

Revision ID: 60447c02465c
Revises: e3f8f5623053
Create Date: 2025-05-05 17:59:12.082514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60447c02465c'
down_revision: Union[str, None] = 'e3f8f5623053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_entries_entry_rss_guid', table_name='news_entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_news_entries_entry_rss_guid', 'news_entries', ['entry_rss_guid'], unique=True)
    # ### end Alembic commands ###
