"""empty message

Revision ID: 6e8c2122548c
Revises: fe54dfd5edff
Create Date: 2025-05-09 22:21:46.968556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.db.models.common import UserTier

# revision identifiers, used by Alembic.
revision: str = '6e8c2122548c'
down_revision: Union[str, None] = 'fe54dfd5edff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('llm_input_token_count', sa.Integer(), nullable=True),
    sa.Column('llm_output_token_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_log_id'), 'llm_usage_log', ['id'], unique=False)
    op.create_table('news_summary_experiment_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('period_type', sa.Enum('weekly', 'monthly', name='newssummaryperiod'), nullable=True),
    sa.Column('news_chunking_experiment', sa.Enum('AGGREGATE_DAILY', 'EMBEDDING_CLUSTERING', name='newschunkingexperiment'), nullable=True),
    sa.Column('news_preference_application_experiment', sa.Enum('WITH_SUMMARIZATION_PROMPT', 'AFTER_NEW_SUMMARIZATION', name='newspreferenceapplicationexperiment'), nullable=True),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.Column('disliked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_summary_experiment_stats_id'), 'news_summary_experiment_stats', ['id'], unique=False)
    op.add_column('news_summary_entry', sa.Column('period_type', sa.Enum('weekly', 'monthly', name='newssummaryperiod'), nullable=True))
    op.add_column('news_summary_entry', sa.Column('news_chunking_experiment', sa.Enum('AGGREGATE_DAILY', 'EMBEDDING_CLUSTERING', name='newschunkingexperiment'), nullable=True))
    op.add_column('news_summary_entry', sa.Column('news_preference_application_experiment', sa.Enum('WITH_SUMMARIZATION_PROMPT', 'AFTER_NEW_SUMMARIZATION', name='newspreferenceapplicationexperiment'), nullable=True))
    op.drop_index('logical_key', table_name='news_summary_entry')
    op.create_index('logical_key', 'news_summary_entry', ['user_id', 'start_date', 'period_type', 'news_chunking_experiment', 'news_preference_application_experiment', 'display_order_within_period'], unique=True)
    op.drop_column('news_summary_entry', 'end_date')
    user_tier = sa.Enum(UserTier, name="usertier")
    user_tier.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('user_tier', user_tier, nullable=True))
    op.add_column('users', sa.Column('preferred_news_chunking_experiment', sa.Enum('AGGREGATE_DAILY', 'EMBEDDING_CLUSTERING', name='newschunkingexperiment'), nullable=True))
    op.add_column('users', sa.Column('preferred_news_preference_application_experiment', sa.Enum('WITH_SUMMARIZATION_PROMPT', 'AFTER_NEW_SUMMARIZATION', name='newspreferenceapplicationexperiment'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_news_preference_application_experiment')
    op.drop_column('users', 'preferred_news_chunking_experiment')
    op.drop_column('users', 'user_tier')
    op.add_column('news_summary_entry', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index('logical_key', table_name='news_summary_entry')
    op.create_index('logical_key', 'news_summary_entry', ['user_id', 'start_date', 'end_date', 'display_order_within_period'], unique=True)
    op.drop_column('news_summary_entry', 'news_preference_application_experiment')
    op.drop_column('news_summary_entry', 'news_chunking_experiment')
    op.drop_column('news_summary_entry', 'period_type')
    op.drop_index(op.f('ix_news_summary_experiment_stats_id'), table_name='news_summary_experiment_stats')
    op.drop_table('news_summary_experiment_stats')
    op.drop_index(op.f('ix_llm_usage_log_id'), table_name='llm_usage_log')
    op.drop_table('llm_usage_log')
    # ### end Alembic commands ###
