"""empty message

Revision ID: 7c933827327f
Revises: d3c0d2301d4e
Create Date: 2025-06-07 10:47:00.742970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c933827327f'
down_revision: Union[str, None] = 'd3c0d2301d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_summary_entry', sa.Column('clicked_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_summary_entry', 'clicked_time')
    # ### end Alembic commands ###
