"""empty message

Revision ID: 814af2e916d0
Revises: 524f5e7b073d
Create Date: 2025-04-25 22:03:27.238820

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "814af2e916d0"
down_revision: Union[str, None] = "524f5e7b073d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_latency_log", "total_elapsed_time_ms")
    op.drop_column("api_latency_log", "llm_elapsed_time_ms")
    op.add_column(
        "api_latency_log",
        sa.Column("total_elapsed_time_ms", sa.Integer(), nullable=True),
    )
    op.add_column(
        "api_latency_log", sa.Column("llm_elapsed_time_ms", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
