"""empty message

Revision ID: 8db1ef8307da
Revises: 00f009f82c45
Create Date: 2025-04-18 14:35:10.759677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db1ef8307da'
down_revision: Union[str, None] = '00f009f82c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_history', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_conversation_history_user_id'), 'conversation_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_history_user_id'), table_name='conversation_history')
    op.drop_column('conversation_history', 'created_at')
    # ### end Alembic commands ###
