"""empty message

Revision ID: 9af681943909
Revises: 8db1ef8307da
Create Date: 2025-04-18 17:51:16.375129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af681943909'
down_revision: Union[str, None] = '8db1ef8307da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_latency_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('api_path', sa.String(), nullable=True),
    sa.Column('total_elapsed_time_ms', sa.Interval(), nullable=True),
    sa.Column('llm_input_token_count', sa.Integer(), nullable=True),
    sa.Column('llm_output_token_count', sa.Integer(), nullable=True),
    sa.Column('llm_elapsed_time_ms', sa.Interval(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_latency_log_id'), 'api_latency_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_latency_log_id'), table_name='api_latency_log')
    op.drop_table('api_latency_log')
    # ### end Alembic commands ###
