"""empty message

Revision ID: 9e20f016690c
Revises: 7c933827327f
Create Date: 2025-06-13 23:16:52.893401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e20f016690c'
down_revision: Union[str, None] = '7c933827327f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("ALTER TYPE public.conversationtype ADD VALUE 'news_research'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
