"""empty message

Revision ID: a178176b4df8
Revises: 4231794b9b2b
Create Date: 2025-05-22 22:16:16.489727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a178176b4df8'
down_revision: Union[str, None] = '4231794b9b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE public.newspreferenceapplicationexperiment ADD VALUE 'APPLY_PREFERENCE'")
    op.execute("ALTER TYPE public.newspreferenceapplicationexperiment ADD VALUE 'NO_PREFERENCE'")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
