"""empty message

Revision ID: babf4dff2f10
Revises: ee5c046ef18f
Create Date: 2025-05-30 19:21:35.301523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from backend.db.models.common import MessageType

# revision identifiers, used by Alembic.
revision: str = 'babf4dff2f10'
down_revision: Union[str, None] = 'ee5c046ef18f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    message_type = sa.Enum(MessageType, name="messagetype")
    message_type.create(op.get_bind(), checkfirst=True)
    op.add_column('conversation_history', sa.Column('message_type', message_type, nullable=True))
    op.drop_column('conversation_history', 'role')
    op.drop_column('conversation_history', 'lang_chain_message_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_history', sa.Column('lang_chain_message_type', postgresql.ENUM('HUMAN', 'AI', 'SYSTEM', 'TOOL', 'UNKNOWN', name='langchainmessagetype'), autoincrement=False, nullable=True))
    op.add_column('conversation_history', sa.Column('role', postgresql.ENUM('user', 'system', 'unknown', name='chatmessagegeneratorrole'), autoincrement=False, nullable=True))
    op.drop_column('conversation_history', 'message_type')
    # ### end Alembic commands ###
