"""empty message

Revision ID: d3c0d2301d4e
Revises: 5525e38a8016
Create Date: 2025-06-04 20:54:10.256862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import vector


# revision identifiers, used by Alembic.
revision: str = 'd3c0d2301d4e'
down_revision: Union[str, None] = '5525e38a8016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_entries', sa.Column('summary_clustering_embedding', vector.VECTOR(dim=768), nullable=True))
    op.add_column('news_entries', sa.Column('summary_document_retrieval_embedding', vector.VECTOR(dim=768), nullable=True))
    op.drop_column('news_entries', 'summary_embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_entries', sa.Column('summary_embedding', vector.VECTOR(dim=768), autoincrement=False, nullable=True))
    op.drop_column('news_entries', 'summary_document_retrieval_embedding')
    op.drop_column('news_entries', 'summary_clustering_embedding')
    # ### end Alembic commands ###
