"""news summary

Revision ID: e3f8f5623053
Revises: 814af2e916d0
Create Date: 2025-05-05 13:24:05.159370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3f8f5623053'
down_revision: Union[str, None] = '814af2e916d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_summary_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('reference_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('clicked', sa.Boolean(), nullable=True),
    sa.Column('display_order_within_period', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_summary_entry_id'), 'news_summary_entry', ['id'], unique=False)
    op.create_index('logical_key', 'news_summary_entry', ['user_id', 'start_date', 'end_date', 'display_order_within_period'], unique=True)
    op.drop_index('ix_news_summaries_id', table_name='news_summaries')
    op.drop_table('news_summaries')
    op.drop_column('news_entries', 'content')
    op.add_column('news_preference_versions', sa.Column('causal_clicked_news_summary_entry_id', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('news_preference_versions', 'causal_clicked_news_summary')
    op.drop_column('rss_feeds', 'xml_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rss_feeds', sa.Column('xml_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('news_preference_versions', sa.Column('causal_clicked_news_summary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('news_preference_versions', 'causal_clicked_news_summary_entry_id')
    op.add_column('news_entries', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('news_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='news_summaries_pkey')
    )
    op.create_index('ix_news_summaries_id', 'news_summaries', ['id'], unique=False)
    op.drop_index('logical_key', table_name='news_summary_entry')
    op.drop_index(op.f('ix_news_summary_entry_id'), table_name='news_summary_entry')
    op.drop_table('news_summary_entry')
    # ### end Alembic commands ###
