"""empty message

Revision ID: ee5c046ef18f
Revises: 15b397869d7c
Create Date: 2025-05-26 10:30:11.062557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee5c046ef18f'
down_revision: Union[str, None] = '15b397869d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_summary_entry', sa.Column('expanded_content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_summary_entry', 'expanded_content')
    # ### end Alembic commands ###
