"""empty message

Revision ID: f2b2d24f4355
Revises: 9e20f016690c
Create Date: 2025-06-16 23:33:11.184710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2b2d24f4355'
down_revision: Union[str, None] = '9e20f016690c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_entries', 'crawl_time',
        server_default=sa.func.now(), existing_type=sa.Date())
    op.alter_column('news_summary_entry', 'creation_time',
        server_default=sa.func.now(), existing_type=sa.Date())
    op.alter_column('news_preference_versions', 'created_at',
        server_default=sa.func.now(), existing_type=sa.Date())
    op.alter_column('api_latency_log', 'created_at',
        server_default=sa.func.now(), existing_type=sa.Date())
    op.alter_column('llm_usage_log', 'created_at',
        server_default=sa.func.now(), existing_type=sa.Date())
    op.alter_column('users', 'created_at',
        server_default=sa.func.now(), existing_type=sa.Date())
    op.alter_column('conversation_history', 'created_at',
        server_default=sa.func.now(), existing_type=sa.Date())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
