"""empty message

Revision ID: fe54dfd5edff
Revises: 974b9bda3cac
Create Date: 2025-05-07 22:16:49.335893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe54dfd5edff'
down_revision: Union[str, None] = '974b9bda3cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_entries', sa.Column('pub_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_entries', 'pub_time')
    # ### end Alembic commands ###
